project_id = "dyowjavinealuqewfrwa"

[api]
enabled = true
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]

[auth]
enabled = true

[storage]
enabled = true

[functions.api-v1]
verify_jwt = false
